#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKT.RubberTraceSystem.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="YKT.RubberTraceSystem.Database")]
	public partial class DataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insert班别(班别 instance);
    partial void Update班别(班别 instance);
    partial void Delete班别(班别 instance);
    partial void Insert处理方法(处理方法 instance);
    partial void Update处理方法(处理方法 instance);
    partial void Delete处理方法(处理方法 instance);
    partial void Insert机台(机台 instance);
    partial void Update机台(机台 instance);
    partial void Delete机台(机台 instance);
    partial void Insert检验修边(检验修边 instance);
    partial void Update检验修边(检验修边 instance);
    partial void Delete检验修边(检验修边 instance);
    partial void Insert胶料入库(胶料入库 instance);
    partial void Update胶料入库(胶料入库 instance);
    partial void Delete胶料入库(胶料入库 instance);
    partial void Insert帘布入库(帘布入库 instance);
    partial void Update帘布入库(帘布入库 instance);
    partial void Delete帘布入库(帘布入库 instance);
    partial void Insert皮囊硫化(皮囊硫化 instance);
    partial void Update皮囊硫化(皮囊硫化 instance);
    partial void Delete皮囊硫化(皮囊硫化 instance);
    partial void Insert员工(员工 instance);
    partial void Update员工(员工 instance);
    partial void Delete员工(员工 instance);
    partial void Insert皮囊成型(皮囊成型 instance);
    partial void Update皮囊成型(皮囊成型 instance);
    partial void Delete皮囊成型(皮囊成型 instance);
    partial void Insert橡胶薄片(橡胶薄片 instance);
    partial void Update橡胶薄片(橡胶薄片 instance);
    partial void Delete橡胶薄片(橡胶薄片 instance);
    partial void Insert帘布流转(帘布流转 instance);
    partial void Update帘布流转(帘布流转 instance);
    partial void Delete帘布流转(帘布流转 instance);
    #endregion
		
		public DataDataContext() : 
				base(global::YKT.RubberTraceSystem.Data.Properties.Settings.Default.YKT_RubberTraceSystem_DatabaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<班别> 班别s
		{
			get
			{
				return this.GetTable<班别>();
			}
		}
		
		public System.Data.Linq.Table<处理方法> 处理方法s
		{
			get
			{
				return this.GetTable<处理方法>();
			}
		}
		
		public System.Data.Linq.Table<机台> 机台s
		{
			get
			{
				return this.GetTable<机台>();
			}
		}
		
		public System.Data.Linq.Table<检验修边> 检验修边s
		{
			get
			{
				return this.GetTable<检验修边>();
			}
		}
		
		public System.Data.Linq.Table<胶料入库> 胶料入库s
		{
			get
			{
				return this.GetTable<胶料入库>();
			}
		}
		
		public System.Data.Linq.Table<帘布入库> 帘布入库s
		{
			get
			{
				return this.GetTable<帘布入库>();
			}
		}
		
		public System.Data.Linq.Table<皮囊硫化> 皮囊硫化s
		{
			get
			{
				return this.GetTable<皮囊硫化>();
			}
		}
		
		public System.Data.Linq.Table<员工> 员工s
		{
			get
			{
				return this.GetTable<员工>();
			}
		}
		
		public System.Data.Linq.Table<皮囊成型> 皮囊成型s
		{
			get
			{
				return this.GetTable<皮囊成型>();
			}
		}
		
		public System.Data.Linq.Table<橡胶薄片> 橡胶薄片s
		{
			get
			{
				return this.GetTable<橡胶薄片>();
			}
		}
		
		public System.Data.Linq.Table<帘布流转> 帘布流转s
		{
			get
			{
				return this.GetTable<帘布流转>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.班别")]
	public partial class 班别 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _班别1;
		
		private System.DateTime _登记时间;
		
		private bool _删除;
		
		private EntitySet<员工> _员工s;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void On班别1Changing(string value);
    partial void On班别1Changed();
    partial void On登记时间Changing(System.DateTime value);
    partial void On登记时间Changed();
    partial void On删除Changing(bool value);
    partial void On删除Changed();
    #endregion
		
		public 班别()
		{
			this._员工s = new EntitySet<员工>(new Action<员工>(this.attach_员工s), new Action<员工>(this.detach_员工s));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="班别", Storage="_班别1", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string 班别1
		{
			get
			{
				return this._班别1;
			}
			set
			{
				if ((this._班别1 != value))
				{
					this.On班别1Changing(value);
					this.SendPropertyChanging();
					this._班别1 = value;
					this.SendPropertyChanged("班别1");
					this.On班别1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_登记时间", DbType="DateTime NOT NULL")]
		public System.DateTime 登记时间
		{
			get
			{
				return this._登记时间;
			}
			set
			{
				if ((this._登记时间 != value))
				{
					this.On登记时间Changing(value);
					this.SendPropertyChanging();
					this._登记时间 = value;
					this.SendPropertyChanged("登记时间");
					this.On登记时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_删除", DbType="Bit NOT NULL")]
		public bool 删除
		{
			get
			{
				return this._删除;
			}
			set
			{
				if ((this._删除 != value))
				{
					this.On删除Changing(value);
					this.SendPropertyChanging();
					this._删除 = value;
					this.SendPropertyChanged("删除");
					this.On删除Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="班别_员工", Storage="_员工s", ThisKey="Id", OtherKey="班别")]
		public EntitySet<员工> 员工s
		{
			get
			{
				return this._员工s;
			}
			set
			{
				this._员工s.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_员工s(员工 entity)
		{
			this.SendPropertyChanging();
			entity.班别1 = this;
		}
		
		private void detach_员工s(员工 entity)
		{
			this.SendPropertyChanging();
			entity.班别1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.处理方法")]
	public partial class 处理方法 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _处理方法1;
		
		private string _附件;
		
		private System.DateTime _登记时间;
		
		private bool _删除;
		
		private EntitySet<检验修边> _检验修边s;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void On处理方法1Changing(string value);
    partial void On处理方法1Changed();
    partial void On附件Changing(string value);
    partial void On附件Changed();
    partial void On登记时间Changing(System.DateTime value);
    partial void On登记时间Changed();
    partial void On删除Changing(bool value);
    partial void On删除Changed();
    #endregion
		
		public 处理方法()
		{
			this._检验修边s = new EntitySet<检验修边>(new Action<检验修边>(this.attach_检验修边s), new Action<检验修边>(this.detach_检验修边s));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="处理方法", Storage="_处理方法1", DbType="NChar(200) NOT NULL", CanBeNull=false)]
		public string 处理方法1
		{
			get
			{
				return this._处理方法1;
			}
			set
			{
				if ((this._处理方法1 != value))
				{
					this.On处理方法1Changing(value);
					this.SendPropertyChanging();
					this._处理方法1 = value;
					this.SendPropertyChanged("处理方法1");
					this.On处理方法1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_附件", DbType="NChar(200)")]
		public string 附件
		{
			get
			{
				return this._附件;
			}
			set
			{
				if ((this._附件 != value))
				{
					this.On附件Changing(value);
					this.SendPropertyChanging();
					this._附件 = value;
					this.SendPropertyChanged("附件");
					this.On附件Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_登记时间", DbType="DateTime NOT NULL")]
		public System.DateTime 登记时间
		{
			get
			{
				return this._登记时间;
			}
			set
			{
				if ((this._登记时间 != value))
				{
					this.On登记时间Changing(value);
					this.SendPropertyChanging();
					this._登记时间 = value;
					this.SendPropertyChanged("登记时间");
					this.On登记时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_删除", DbType="Bit NOT NULL")]
		public bool 删除
		{
			get
			{
				return this._删除;
			}
			set
			{
				if ((this._删除 != value))
				{
					this.On删除Changing(value);
					this.SendPropertyChanging();
					this._删除 = value;
					this.SendPropertyChanged("删除");
					this.On删除Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="处理方法_检验修边", Storage="_检验修边s", ThisKey="Id", OtherKey="处理方法")]
		public EntitySet<检验修边> 检验修边s
		{
			get
			{
				return this._检验修边s;
			}
			set
			{
				this._检验修边s.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_检验修边s(检验修边 entity)
		{
			this.SendPropertyChanging();
			entity.处理方法1 = this;
		}
		
		private void detach_检验修边s(检验修边 entity)
		{
			this.SendPropertyChanging();
			entity.处理方法1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.机台")]
	public partial class 机台 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _机台编号;
		
		private string _机台名称;
		
		private string _机台描述;
		
		private System.DateTime _登记时间;
		
		private bool _删除;
		
		private EntitySet<皮囊硫化> _皮囊硫化s;
		
		private EntitySet<皮囊成型> _皮囊成型s;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void On机台编号Changing(string value);
    partial void On机台编号Changed();
    partial void On机台名称Changing(string value);
    partial void On机台名称Changed();
    partial void On机台描述Changing(string value);
    partial void On机台描述Changed();
    partial void On登记时间Changing(System.DateTime value);
    partial void On登记时间Changed();
    partial void On删除Changing(bool value);
    partial void On删除Changed();
    #endregion
		
		public 机台()
		{
			this._皮囊硫化s = new EntitySet<皮囊硫化>(new Action<皮囊硫化>(this.attach_皮囊硫化s), new Action<皮囊硫化>(this.detach_皮囊硫化s));
			this._皮囊成型s = new EntitySet<皮囊成型>(new Action<皮囊成型>(this.attach_皮囊成型s), new Action<皮囊成型>(this.detach_皮囊成型s));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_机台编号", DbType="NChar(200) NOT NULL", CanBeNull=false)]
		public string 机台编号
		{
			get
			{
				return this._机台编号;
			}
			set
			{
				if ((this._机台编号 != value))
				{
					this.On机台编号Changing(value);
					this.SendPropertyChanging();
					this._机台编号 = value;
					this.SendPropertyChanged("机台编号");
					this.On机台编号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_机台名称", DbType="NChar(200)")]
		public string 机台名称
		{
			get
			{
				return this._机台名称;
			}
			set
			{
				if ((this._机台名称 != value))
				{
					this.On机台名称Changing(value);
					this.SendPropertyChanging();
					this._机台名称 = value;
					this.SendPropertyChanged("机台名称");
					this.On机台名称Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_机台描述", DbType="NChar(200)")]
		public string 机台描述
		{
			get
			{
				return this._机台描述;
			}
			set
			{
				if ((this._机台描述 != value))
				{
					this.On机台描述Changing(value);
					this.SendPropertyChanging();
					this._机台描述 = value;
					this.SendPropertyChanged("机台描述");
					this.On机台描述Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_登记时间", DbType="DateTime NOT NULL")]
		public System.DateTime 登记时间
		{
			get
			{
				return this._登记时间;
			}
			set
			{
				if ((this._登记时间 != value))
				{
					this.On登记时间Changing(value);
					this.SendPropertyChanging();
					this._登记时间 = value;
					this.SendPropertyChanged("登记时间");
					this.On登记时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_删除", DbType="Bit NOT NULL")]
		public bool 删除
		{
			get
			{
				return this._删除;
			}
			set
			{
				if ((this._删除 != value))
				{
					this.On删除Changing(value);
					this.SendPropertyChanging();
					this._删除 = value;
					this.SendPropertyChanged("删除");
					this.On删除Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="机台_皮囊硫化", Storage="_皮囊硫化s", ThisKey="Id", OtherKey="生产机台")]
		public EntitySet<皮囊硫化> 皮囊硫化s
		{
			get
			{
				return this._皮囊硫化s;
			}
			set
			{
				this._皮囊硫化s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="机台_皮囊成型", Storage="_皮囊成型s", ThisKey="Id", OtherKey="生产机台")]
		public EntitySet<皮囊成型> 皮囊成型s
		{
			get
			{
				return this._皮囊成型s;
			}
			set
			{
				this._皮囊成型s.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_皮囊硫化s(皮囊硫化 entity)
		{
			this.SendPropertyChanging();
			entity.机台 = this;
		}
		
		private void detach_皮囊硫化s(皮囊硫化 entity)
		{
			this.SendPropertyChanging();
			entity.机台 = null;
		}
		
		private void attach_皮囊成型s(皮囊成型 entity)
		{
			this.SendPropertyChanging();
			entity.机台 = this;
		}
		
		private void detach_皮囊成型s(皮囊成型 entity)
		{
			this.SendPropertyChanging();
			entity.机台 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.检验修边")]
	public partial class 检验修边 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private bool _结果;
		
		private System.Guid _处理方法;
		
		private System.Guid _检验员;
		
		private System.Guid _硫化皮囊;
		
		private System.DateTime _登记时间;
		
		private bool _删除;
		
		private EntityRef<处理方法> _处理方法1;
		
		private EntityRef<皮囊硫化> _皮囊硫化;
		
		private EntityRef<员工> _员工;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void On结果Changing(bool value);
    partial void On结果Changed();
    partial void On处理方法Changing(System.Guid value);
    partial void On处理方法Changed();
    partial void On检验员Changing(System.Guid value);
    partial void On检验员Changed();
    partial void On硫化皮囊Changing(System.Guid value);
    partial void On硫化皮囊Changed();
    partial void On登记时间Changing(System.DateTime value);
    partial void On登记时间Changed();
    partial void On删除Changing(bool value);
    partial void On删除Changed();
    #endregion
		
		public 检验修边()
		{
			this._处理方法1 = default(EntityRef<处理方法>);
			this._皮囊硫化 = default(EntityRef<皮囊硫化>);
			this._员工 = default(EntityRef<员工>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_结果", DbType="Bit NOT NULL")]
		public bool 结果
		{
			get
			{
				return this._结果;
			}
			set
			{
				if ((this._结果 != value))
				{
					this.On结果Changing(value);
					this.SendPropertyChanging();
					this._结果 = value;
					this.SendPropertyChanged("结果");
					this.On结果Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_处理方法", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid 处理方法
		{
			get
			{
				return this._处理方法;
			}
			set
			{
				if ((this._处理方法 != value))
				{
					if (this._处理方法1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.On处理方法Changing(value);
					this.SendPropertyChanging();
					this._处理方法 = value;
					this.SendPropertyChanged("处理方法");
					this.On处理方法Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_检验员", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid 检验员
		{
			get
			{
				return this._检验员;
			}
			set
			{
				if ((this._检验员 != value))
				{
					if (this._员工.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.On检验员Changing(value);
					this.SendPropertyChanging();
					this._检验员 = value;
					this.SendPropertyChanged("检验员");
					this.On检验员Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_硫化皮囊", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid 硫化皮囊
		{
			get
			{
				return this._硫化皮囊;
			}
			set
			{
				if ((this._硫化皮囊 != value))
				{
					if (this._皮囊硫化.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.On硫化皮囊Changing(value);
					this.SendPropertyChanging();
					this._硫化皮囊 = value;
					this.SendPropertyChanged("硫化皮囊");
					this.On硫化皮囊Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_登记时间", DbType="DateTime NOT NULL")]
		public System.DateTime 登记时间
		{
			get
			{
				return this._登记时间;
			}
			set
			{
				if ((this._登记时间 != value))
				{
					this.On登记时间Changing(value);
					this.SendPropertyChanging();
					this._登记时间 = value;
					this.SendPropertyChanged("登记时间");
					this.On登记时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_删除", DbType="Bit NOT NULL")]
		public bool 删除
		{
			get
			{
				return this._删除;
			}
			set
			{
				if ((this._删除 != value))
				{
					this.On删除Changing(value);
					this.SendPropertyChanging();
					this._删除 = value;
					this.SendPropertyChanged("删除");
					this.On删除Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="处理方法_检验修边", Storage="_处理方法1", ThisKey="处理方法", OtherKey="Id", IsForeignKey=true)]
		public 处理方法 处理方法1
		{
			get
			{
				return this._处理方法1.Entity;
			}
			set
			{
				处理方法 previousValue = this._处理方法1.Entity;
				if (((previousValue != value) 
							|| (this._处理方法1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._处理方法1.Entity = null;
						previousValue.检验修边s.Remove(this);
					}
					this._处理方法1.Entity = value;
					if ((value != null))
					{
						value.检验修边s.Add(this);
						this._处理方法 = value.Id;
					}
					else
					{
						this._处理方法 = default(System.Guid);
					}
					this.SendPropertyChanged("处理方法1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="皮囊硫化_检验修边", Storage="_皮囊硫化", ThisKey="硫化皮囊", OtherKey="Id", IsForeignKey=true)]
		public 皮囊硫化 皮囊硫化
		{
			get
			{
				return this._皮囊硫化.Entity;
			}
			set
			{
				皮囊硫化 previousValue = this._皮囊硫化.Entity;
				if (((previousValue != value) 
							|| (this._皮囊硫化.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._皮囊硫化.Entity = null;
						previousValue.检验修边s.Remove(this);
					}
					this._皮囊硫化.Entity = value;
					if ((value != null))
					{
						value.检验修边s.Add(this);
						this._硫化皮囊 = value.Id;
					}
					else
					{
						this._硫化皮囊 = default(System.Guid);
					}
					this.SendPropertyChanged("皮囊硫化");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="员工_检验修边", Storage="_员工", ThisKey="检验员", OtherKey="Id", IsForeignKey=true)]
		public 员工 员工
		{
			get
			{
				return this._员工.Entity;
			}
			set
			{
				员工 previousValue = this._员工.Entity;
				if (((previousValue != value) 
							|| (this._员工.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._员工.Entity = null;
						previousValue.检验修边s.Remove(this);
					}
					this._员工.Entity = value;
					if ((value != null))
					{
						value.检验修边s.Add(this);
						this._检验员 = value.Id;
					}
					else
					{
						this._检验员 = default(System.Guid);
					}
					this.SendPropertyChanged("员工");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.胶料入库")]
	public partial class 胶料入库 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _胶料牌号;
		
		private string _箱号;
		
		private string _生产线号;
		
		private string _供应商产品代号;
		
		private string _生产日期;
		
		private string _批次号;
		
		private double _重量;
		
		private System.DateTime _登记时间;
		
		private bool _删除;
		
		private EntitySet<橡胶薄片> _橡胶薄片s;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void On胶料牌号Changing(string value);
    partial void On胶料牌号Changed();
    partial void On箱号Changing(string value);
    partial void On箱号Changed();
    partial void On生产线号Changing(string value);
    partial void On生产线号Changed();
    partial void On供应商产品代号Changing(string value);
    partial void On供应商产品代号Changed();
    partial void On生产日期Changing(string value);
    partial void On生产日期Changed();
    partial void On批次号Changing(string value);
    partial void On批次号Changed();
    partial void On重量Changing(double value);
    partial void On重量Changed();
    partial void On登记时间Changing(System.DateTime value);
    partial void On登记时间Changed();
    partial void On删除Changing(bool value);
    partial void On删除Changed();
    #endregion
		
		public 胶料入库()
		{
			this._橡胶薄片s = new EntitySet<橡胶薄片>(new Action<橡胶薄片>(this.attach_橡胶薄片s), new Action<橡胶薄片>(this.detach_橡胶薄片s));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_胶料牌号", DbType="NChar(200) NOT NULL", CanBeNull=false)]
		public string 胶料牌号
		{
			get
			{
				return this._胶料牌号;
			}
			set
			{
				if ((this._胶料牌号 != value))
				{
					this.On胶料牌号Changing(value);
					this.SendPropertyChanging();
					this._胶料牌号 = value;
					this.SendPropertyChanged("胶料牌号");
					this.On胶料牌号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_箱号", DbType="NChar(200)")]
		public string 箱号
		{
			get
			{
				return this._箱号;
			}
			set
			{
				if ((this._箱号 != value))
				{
					this.On箱号Changing(value);
					this.SendPropertyChanging();
					this._箱号 = value;
					this.SendPropertyChanged("箱号");
					this.On箱号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_生产线号", DbType="NChar(200)")]
		public string 生产线号
		{
			get
			{
				return this._生产线号;
			}
			set
			{
				if ((this._生产线号 != value))
				{
					this.On生产线号Changing(value);
					this.SendPropertyChanging();
					this._生产线号 = value;
					this.SendPropertyChanged("生产线号");
					this.On生产线号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_供应商产品代号", DbType="NChar(200)")]
		public string 供应商产品代号
		{
			get
			{
				return this._供应商产品代号;
			}
			set
			{
				if ((this._供应商产品代号 != value))
				{
					this.On供应商产品代号Changing(value);
					this.SendPropertyChanging();
					this._供应商产品代号 = value;
					this.SendPropertyChanged("供应商产品代号");
					this.On供应商产品代号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_生产日期", DbType="NChar(200) NOT NULL", CanBeNull=false)]
		public string 生产日期
		{
			get
			{
				return this._生产日期;
			}
			set
			{
				if ((this._生产日期 != value))
				{
					this.On生产日期Changing(value);
					this.SendPropertyChanging();
					this._生产日期 = value;
					this.SendPropertyChanged("生产日期");
					this.On生产日期Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_批次号", DbType="NChar(200) NOT NULL", CanBeNull=false)]
		public string 批次号
		{
			get
			{
				return this._批次号;
			}
			set
			{
				if ((this._批次号 != value))
				{
					this.On批次号Changing(value);
					this.SendPropertyChanging();
					this._批次号 = value;
					this.SendPropertyChanged("批次号");
					this.On批次号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_重量", DbType="Float NOT NULL")]
		public double 重量
		{
			get
			{
				return this._重量;
			}
			set
			{
				if ((this._重量 != value))
				{
					this.On重量Changing(value);
					this.SendPropertyChanging();
					this._重量 = value;
					this.SendPropertyChanged("重量");
					this.On重量Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_登记时间", DbType="DateTime NOT NULL")]
		public System.DateTime 登记时间
		{
			get
			{
				return this._登记时间;
			}
			set
			{
				if ((this._登记时间 != value))
				{
					this.On登记时间Changing(value);
					this.SendPropertyChanging();
					this._登记时间 = value;
					this.SendPropertyChanged("登记时间");
					this.On登记时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_删除", DbType="Bit NOT NULL")]
		public bool 删除
		{
			get
			{
				return this._删除;
			}
			set
			{
				if ((this._删除 != value))
				{
					this.On删除Changing(value);
					this.SendPropertyChanging();
					this._删除 = value;
					this.SendPropertyChanged("删除");
					this.On删除Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="胶料入库_橡胶薄片", Storage="_橡胶薄片s", ThisKey="Id", OtherKey="胶料批号")]
		public EntitySet<橡胶薄片> 橡胶薄片s
		{
			get
			{
				return this._橡胶薄片s;
			}
			set
			{
				this._橡胶薄片s.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_橡胶薄片s(橡胶薄片 entity)
		{
			this.SendPropertyChanging();
			entity.胶料入库 = this;
		}
		
		private void detach_橡胶薄片s(橡胶薄片 entity)
		{
			this.SendPropertyChanging();
			entity.胶料入库 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.帘布入库")]
	public partial class 帘布入库 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _帘布代号;
		
		private string _胶料;
		
		private double _帘布长度;
		
		private System.Nullable<double> _生产序号;
		
		private string _生产日期;
		
		private string _有效日期;
		
		private double _重量;
		
		private System.DateTime _登记时间;
		
		private bool _删除;
		
		private EntitySet<帘布流转> _帘布流转s;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void On帘布代号Changing(string value);
    partial void On帘布代号Changed();
    partial void On胶料Changing(string value);
    partial void On胶料Changed();
    partial void On帘布长度Changing(double value);
    partial void On帘布长度Changed();
    partial void On生产序号Changing(System.Nullable<double> value);
    partial void On生产序号Changed();
    partial void On生产日期Changing(string value);
    partial void On生产日期Changed();
    partial void On有效日期Changing(string value);
    partial void On有效日期Changed();
    partial void On重量Changing(double value);
    partial void On重量Changed();
    partial void On登记时间Changing(System.DateTime value);
    partial void On登记时间Changed();
    partial void On删除Changing(bool value);
    partial void On删除Changed();
    #endregion
		
		public 帘布入库()
		{
			this._帘布流转s = new EntitySet<帘布流转>(new Action<帘布流转>(this.attach_帘布流转s), new Action<帘布流转>(this.detach_帘布流转s));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_帘布代号", DbType="NChar(200) NOT NULL", CanBeNull=false)]
		public string 帘布代号
		{
			get
			{
				return this._帘布代号;
			}
			set
			{
				if ((this._帘布代号 != value))
				{
					this.On帘布代号Changing(value);
					this.SendPropertyChanging();
					this._帘布代号 = value;
					this.SendPropertyChanged("帘布代号");
					this.On帘布代号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_胶料", DbType="NChar(200)")]
		public string 胶料
		{
			get
			{
				return this._胶料;
			}
			set
			{
				if ((this._胶料 != value))
				{
					this.On胶料Changing(value);
					this.SendPropertyChanging();
					this._胶料 = value;
					this.SendPropertyChanged("胶料");
					this.On胶料Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_帘布长度", DbType="Float NOT NULL")]
		public double 帘布长度
		{
			get
			{
				return this._帘布长度;
			}
			set
			{
				if ((this._帘布长度 != value))
				{
					this.On帘布长度Changing(value);
					this.SendPropertyChanging();
					this._帘布长度 = value;
					this.SendPropertyChanged("帘布长度");
					this.On帘布长度Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_生产序号", DbType="Float")]
		public System.Nullable<double> 生产序号
		{
			get
			{
				return this._生产序号;
			}
			set
			{
				if ((this._生产序号 != value))
				{
					this.On生产序号Changing(value);
					this.SendPropertyChanging();
					this._生产序号 = value;
					this.SendPropertyChanged("生产序号");
					this.On生产序号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_生产日期", DbType="NChar(200) NOT NULL", CanBeNull=false)]
		public string 生产日期
		{
			get
			{
				return this._生产日期;
			}
			set
			{
				if ((this._生产日期 != value))
				{
					this.On生产日期Changing(value);
					this.SendPropertyChanging();
					this._生产日期 = value;
					this.SendPropertyChanged("生产日期");
					this.On生产日期Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_有效日期", DbType="NChar(200) NOT NULL", CanBeNull=false)]
		public string 有效日期
		{
			get
			{
				return this._有效日期;
			}
			set
			{
				if ((this._有效日期 != value))
				{
					this.On有效日期Changing(value);
					this.SendPropertyChanging();
					this._有效日期 = value;
					this.SendPropertyChanged("有效日期");
					this.On有效日期Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_重量", DbType="Float NOT NULL")]
		public double 重量
		{
			get
			{
				return this._重量;
			}
			set
			{
				if ((this._重量 != value))
				{
					this.On重量Changing(value);
					this.SendPropertyChanging();
					this._重量 = value;
					this.SendPropertyChanged("重量");
					this.On重量Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_登记时间", DbType="DateTime NOT NULL")]
		public System.DateTime 登记时间
		{
			get
			{
				return this._登记时间;
			}
			set
			{
				if ((this._登记时间 != value))
				{
					this.On登记时间Changing(value);
					this.SendPropertyChanging();
					this._登记时间 = value;
					this.SendPropertyChanged("登记时间");
					this.On登记时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_删除", DbType="Bit NOT NULL")]
		public bool 删除
		{
			get
			{
				return this._删除;
			}
			set
			{
				if ((this._删除 != value))
				{
					this.On删除Changing(value);
					this.SendPropertyChanging();
					this._删除 = value;
					this.SendPropertyChanged("删除");
					this.On删除Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="帘布入库_帘布流转", Storage="_帘布流转s", ThisKey="Id", OtherKey="帘布批号")]
		public EntitySet<帘布流转> 帘布流转s
		{
			get
			{
				return this._帘布流转s;
			}
			set
			{
				this._帘布流转s.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_帘布流转s(帘布流转 entity)
		{
			this.SendPropertyChanging();
			entity.帘布入库 = this;
		}
		
		private void detach_帘布流转s(帘布流转 entity)
		{
			this.SendPropertyChanging();
			entity.帘布入库 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.皮囊硫化")]
	public partial class 皮囊硫化 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _产品型号;
		
		private System.Guid _生产机台;
		
		private System.Guid _作业员;
		
		private System.Guid _成型皮囊;
		
		private System.Nullable<double> _硫化温度;
		
		private System.Nullable<double> _硫化时间;
		
		private System.Nullable<System.Guid> _模具;
		
		private System.DateTime _登记时间;
		
		private bool _删除;
		
		private EntitySet<检验修边> _检验修边s;
		
		private EntityRef<机台> _机台;
		
		private EntityRef<员工> _员工;
		
		private EntityRef<皮囊成型> _皮囊成型;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void On产品型号Changing(string value);
    partial void On产品型号Changed();
    partial void On生产机台Changing(System.Guid value);
    partial void On生产机台Changed();
    partial void On作业员Changing(System.Guid value);
    partial void On作业员Changed();
    partial void On成型皮囊Changing(System.Guid value);
    partial void On成型皮囊Changed();
    partial void On硫化温度Changing(System.Nullable<double> value);
    partial void On硫化温度Changed();
    partial void On硫化时间Changing(System.Nullable<double> value);
    partial void On硫化时间Changed();
    partial void On模具Changing(System.Nullable<System.Guid> value);
    partial void On模具Changed();
    partial void On登记时间Changing(System.DateTime value);
    partial void On登记时间Changed();
    partial void On删除Changing(bool value);
    partial void On删除Changed();
    #endregion
		
		public 皮囊硫化()
		{
			this._检验修边s = new EntitySet<检验修边>(new Action<检验修边>(this.attach_检验修边s), new Action<检验修边>(this.detach_检验修边s));
			this._机台 = default(EntityRef<机台>);
			this._员工 = default(EntityRef<员工>);
			this._皮囊成型 = default(EntityRef<皮囊成型>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_产品型号", DbType="NChar(200) NOT NULL", CanBeNull=false)]
		public string 产品型号
		{
			get
			{
				return this._产品型号;
			}
			set
			{
				if ((this._产品型号 != value))
				{
					this.On产品型号Changing(value);
					this.SendPropertyChanging();
					this._产品型号 = value;
					this.SendPropertyChanged("产品型号");
					this.On产品型号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_生产机台", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid 生产机台
		{
			get
			{
				return this._生产机台;
			}
			set
			{
				if ((this._生产机台 != value))
				{
					if (this._机台.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.On生产机台Changing(value);
					this.SendPropertyChanging();
					this._生产机台 = value;
					this.SendPropertyChanged("生产机台");
					this.On生产机台Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_作业员", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid 作业员
		{
			get
			{
				return this._作业员;
			}
			set
			{
				if ((this._作业员 != value))
				{
					if (this._员工.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.On作业员Changing(value);
					this.SendPropertyChanging();
					this._作业员 = value;
					this.SendPropertyChanged("作业员");
					this.On作业员Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_成型皮囊", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid 成型皮囊
		{
			get
			{
				return this._成型皮囊;
			}
			set
			{
				if ((this._成型皮囊 != value))
				{
					if (this._皮囊成型.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.On成型皮囊Changing(value);
					this.SendPropertyChanging();
					this._成型皮囊 = value;
					this.SendPropertyChanged("成型皮囊");
					this.On成型皮囊Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_硫化温度", DbType="Float")]
		public System.Nullable<double> 硫化温度
		{
			get
			{
				return this._硫化温度;
			}
			set
			{
				if ((this._硫化温度 != value))
				{
					this.On硫化温度Changing(value);
					this.SendPropertyChanging();
					this._硫化温度 = value;
					this.SendPropertyChanged("硫化温度");
					this.On硫化温度Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_硫化时间", DbType="Float")]
		public System.Nullable<double> 硫化时间
		{
			get
			{
				return this._硫化时间;
			}
			set
			{
				if ((this._硫化时间 != value))
				{
					this.On硫化时间Changing(value);
					this.SendPropertyChanging();
					this._硫化时间 = value;
					this.SendPropertyChanged("硫化时间");
					this.On硫化时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_模具", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> 模具
		{
			get
			{
				return this._模具;
			}
			set
			{
				if ((this._模具 != value))
				{
					this.On模具Changing(value);
					this.SendPropertyChanging();
					this._模具 = value;
					this.SendPropertyChanged("模具");
					this.On模具Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_登记时间", DbType="DateTime NOT NULL")]
		public System.DateTime 登记时间
		{
			get
			{
				return this._登记时间;
			}
			set
			{
				if ((this._登记时间 != value))
				{
					this.On登记时间Changing(value);
					this.SendPropertyChanging();
					this._登记时间 = value;
					this.SendPropertyChanged("登记时间");
					this.On登记时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_删除", DbType="Bit NOT NULL")]
		public bool 删除
		{
			get
			{
				return this._删除;
			}
			set
			{
				if ((this._删除 != value))
				{
					this.On删除Changing(value);
					this.SendPropertyChanging();
					this._删除 = value;
					this.SendPropertyChanged("删除");
					this.On删除Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="皮囊硫化_检验修边", Storage="_检验修边s", ThisKey="Id", OtherKey="硫化皮囊")]
		public EntitySet<检验修边> 检验修边s
		{
			get
			{
				return this._检验修边s;
			}
			set
			{
				this._检验修边s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="机台_皮囊硫化", Storage="_机台", ThisKey="生产机台", OtherKey="Id", IsForeignKey=true)]
		public 机台 机台
		{
			get
			{
				return this._机台.Entity;
			}
			set
			{
				机台 previousValue = this._机台.Entity;
				if (((previousValue != value) 
							|| (this._机台.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._机台.Entity = null;
						previousValue.皮囊硫化s.Remove(this);
					}
					this._机台.Entity = value;
					if ((value != null))
					{
						value.皮囊硫化s.Add(this);
						this._生产机台 = value.Id;
					}
					else
					{
						this._生产机台 = default(System.Guid);
					}
					this.SendPropertyChanged("机台");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="员工_皮囊硫化", Storage="_员工", ThisKey="作业员", OtherKey="Id", IsForeignKey=true)]
		public 员工 员工
		{
			get
			{
				return this._员工.Entity;
			}
			set
			{
				员工 previousValue = this._员工.Entity;
				if (((previousValue != value) 
							|| (this._员工.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._员工.Entity = null;
						previousValue.皮囊硫化s.Remove(this);
					}
					this._员工.Entity = value;
					if ((value != null))
					{
						value.皮囊硫化s.Add(this);
						this._作业员 = value.Id;
					}
					else
					{
						this._作业员 = default(System.Guid);
					}
					this.SendPropertyChanged("员工");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="皮囊成型_皮囊硫化", Storage="_皮囊成型", ThisKey="成型皮囊", OtherKey="Id", IsForeignKey=true)]
		public 皮囊成型 皮囊成型
		{
			get
			{
				return this._皮囊成型.Entity;
			}
			set
			{
				皮囊成型 previousValue = this._皮囊成型.Entity;
				if (((previousValue != value) 
							|| (this._皮囊成型.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._皮囊成型.Entity = null;
						previousValue.皮囊硫化s.Remove(this);
					}
					this._皮囊成型.Entity = value;
					if ((value != null))
					{
						value.皮囊硫化s.Add(this);
						this._成型皮囊 = value.Id;
					}
					else
					{
						this._成型皮囊 = default(System.Guid);
					}
					this.SendPropertyChanged("皮囊成型");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_检验修边s(检验修边 entity)
		{
			this.SendPropertyChanging();
			entity.皮囊硫化 = this;
		}
		
		private void detach_检验修边s(检验修边 entity)
		{
			this.SendPropertyChanging();
			entity.皮囊硫化 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.员工")]
	public partial class 员工 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _姓名;
		
		private System.Guid _班别;
		
		private System.DateTime _登记时间;
		
		private bool _删除;
		
		private EntitySet<检验修边> _检验修边s;
		
		private EntitySet<皮囊硫化> _皮囊硫化s;
		
		private EntitySet<皮囊成型> _皮囊成型s;
		
		private EntitySet<橡胶薄片> _橡胶薄片s;
		
		private EntitySet<帘布流转> _帘布流转s;
		
		private EntityRef<班别> _班别1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void On姓名Changing(string value);
    partial void On姓名Changed();
    partial void On班别Changing(System.Guid value);
    partial void On班别Changed();
    partial void On登记时间Changing(System.DateTime value);
    partial void On登记时间Changed();
    partial void On删除Changing(bool value);
    partial void On删除Changed();
    #endregion
		
		public 员工()
		{
			this._检验修边s = new EntitySet<检验修边>(new Action<检验修边>(this.attach_检验修边s), new Action<检验修边>(this.detach_检验修边s));
			this._皮囊硫化s = new EntitySet<皮囊硫化>(new Action<皮囊硫化>(this.attach_皮囊硫化s), new Action<皮囊硫化>(this.detach_皮囊硫化s));
			this._皮囊成型s = new EntitySet<皮囊成型>(new Action<皮囊成型>(this.attach_皮囊成型s), new Action<皮囊成型>(this.detach_皮囊成型s));
			this._橡胶薄片s = new EntitySet<橡胶薄片>(new Action<橡胶薄片>(this.attach_橡胶薄片s), new Action<橡胶薄片>(this.detach_橡胶薄片s));
			this._帘布流转s = new EntitySet<帘布流转>(new Action<帘布流转>(this.attach_帘布流转s), new Action<帘布流转>(this.detach_帘布流转s));
			this._班别1 = default(EntityRef<班别>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_姓名", DbType="NChar(200) NOT NULL", CanBeNull=false)]
		public string 姓名
		{
			get
			{
				return this._姓名;
			}
			set
			{
				if ((this._姓名 != value))
				{
					this.On姓名Changing(value);
					this.SendPropertyChanging();
					this._姓名 = value;
					this.SendPropertyChanged("姓名");
					this.On姓名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_班别", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid 班别
		{
			get
			{
				return this._班别;
			}
			set
			{
				if ((this._班别 != value))
				{
					if (this._班别1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.On班别Changing(value);
					this.SendPropertyChanging();
					this._班别 = value;
					this.SendPropertyChanged("班别");
					this.On班别Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_登记时间", DbType="DateTime NOT NULL")]
		public System.DateTime 登记时间
		{
			get
			{
				return this._登记时间;
			}
			set
			{
				if ((this._登记时间 != value))
				{
					this.On登记时间Changing(value);
					this.SendPropertyChanging();
					this._登记时间 = value;
					this.SendPropertyChanged("登记时间");
					this.On登记时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_删除", DbType="Bit NOT NULL")]
		public bool 删除
		{
			get
			{
				return this._删除;
			}
			set
			{
				if ((this._删除 != value))
				{
					this.On删除Changing(value);
					this.SendPropertyChanging();
					this._删除 = value;
					this.SendPropertyChanged("删除");
					this.On删除Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="员工_检验修边", Storage="_检验修边s", ThisKey="Id", OtherKey="检验员")]
		public EntitySet<检验修边> 检验修边s
		{
			get
			{
				return this._检验修边s;
			}
			set
			{
				this._检验修边s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="员工_皮囊硫化", Storage="_皮囊硫化s", ThisKey="Id", OtherKey="作业员")]
		public EntitySet<皮囊硫化> 皮囊硫化s
		{
			get
			{
				return this._皮囊硫化s;
			}
			set
			{
				this._皮囊硫化s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="员工_皮囊成型", Storage="_皮囊成型s", ThisKey="Id", OtherKey="作业员")]
		public EntitySet<皮囊成型> 皮囊成型s
		{
			get
			{
				return this._皮囊成型s;
			}
			set
			{
				this._皮囊成型s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="员工_橡胶薄片", Storage="_橡胶薄片s", ThisKey="Id", OtherKey="作业员")]
		public EntitySet<橡胶薄片> 橡胶薄片s
		{
			get
			{
				return this._橡胶薄片s;
			}
			set
			{
				this._橡胶薄片s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="员工_帘布流转", Storage="_帘布流转s", ThisKey="Id", OtherKey="作业员")]
		public EntitySet<帘布流转> 帘布流转s
		{
			get
			{
				return this._帘布流转s;
			}
			set
			{
				this._帘布流转s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="班别_员工", Storage="_班别1", ThisKey="班别", OtherKey="Id", IsForeignKey=true)]
		public 班别 班别1
		{
			get
			{
				return this._班别1.Entity;
			}
			set
			{
				班别 previousValue = this._班别1.Entity;
				if (((previousValue != value) 
							|| (this._班别1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._班别1.Entity = null;
						previousValue.员工s.Remove(this);
					}
					this._班别1.Entity = value;
					if ((value != null))
					{
						value.员工s.Add(this);
						this._班别 = value.Id;
					}
					else
					{
						this._班别 = default(System.Guid);
					}
					this.SendPropertyChanged("班别1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_检验修边s(检验修边 entity)
		{
			this.SendPropertyChanging();
			entity.员工 = this;
		}
		
		private void detach_检验修边s(检验修边 entity)
		{
			this.SendPropertyChanging();
			entity.员工 = null;
		}
		
		private void attach_皮囊硫化s(皮囊硫化 entity)
		{
			this.SendPropertyChanging();
			entity.员工 = this;
		}
		
		private void detach_皮囊硫化s(皮囊硫化 entity)
		{
			this.SendPropertyChanging();
			entity.员工 = null;
		}
		
		private void attach_皮囊成型s(皮囊成型 entity)
		{
			this.SendPropertyChanging();
			entity.员工 = this;
		}
		
		private void detach_皮囊成型s(皮囊成型 entity)
		{
			this.SendPropertyChanging();
			entity.员工 = null;
		}
		
		private void attach_橡胶薄片s(橡胶薄片 entity)
		{
			this.SendPropertyChanging();
			entity.员工 = this;
		}
		
		private void detach_橡胶薄片s(橡胶薄片 entity)
		{
			this.SendPropertyChanging();
			entity.员工 = null;
		}
		
		private void attach_帘布流转s(帘布流转 entity)
		{
			this.SendPropertyChanging();
			entity.员工 = this;
		}
		
		private void detach_帘布流转s(帘布流转 entity)
		{
			this.SendPropertyChanging();
			entity.员工 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.皮囊成型")]
	public partial class 皮囊成型 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _产品型号;
		
		private System.Nullable<System.Guid> _生产机台;
		
		private System.Nullable<System.Guid> _作业员;
		
		private System.Guid _帘布批号;
		
		private System.Guid _外胶片批号;
		
		private System.Guid _内胶片批号;
		
		private System.DateTime _登记时间;
		
		private bool _删除;
		
		private EntitySet<皮囊硫化> _皮囊硫化s;
		
		private EntityRef<机台> _机台;
		
		private EntityRef<员工> _员工;
		
		private EntityRef<橡胶薄片> _橡胶薄片;
		
		private EntityRef<橡胶薄片> _橡胶薄片1;
		
		private EntityRef<帘布流转> _帘布流转;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void On产品型号Changing(string value);
    partial void On产品型号Changed();
    partial void On生产机台Changing(System.Nullable<System.Guid> value);
    partial void On生产机台Changed();
    partial void On作业员Changing(System.Nullable<System.Guid> value);
    partial void On作业员Changed();
    partial void On帘布批号Changing(System.Guid value);
    partial void On帘布批号Changed();
    partial void On外胶片批号Changing(System.Guid value);
    partial void On外胶片批号Changed();
    partial void On内胶片批号Changing(System.Guid value);
    partial void On内胶片批号Changed();
    partial void On登记时间Changing(System.DateTime value);
    partial void On登记时间Changed();
    partial void On删除Changing(bool value);
    partial void On删除Changed();
    #endregion
		
		public 皮囊成型()
		{
			this._皮囊硫化s = new EntitySet<皮囊硫化>(new Action<皮囊硫化>(this.attach_皮囊硫化s), new Action<皮囊硫化>(this.detach_皮囊硫化s));
			this._机台 = default(EntityRef<机台>);
			this._员工 = default(EntityRef<员工>);
			this._橡胶薄片 = default(EntityRef<橡胶薄片>);
			this._橡胶薄片1 = default(EntityRef<橡胶薄片>);
			this._帘布流转 = default(EntityRef<帘布流转>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_产品型号", DbType="NChar(200) NOT NULL", CanBeNull=false)]
		public string 产品型号
		{
			get
			{
				return this._产品型号;
			}
			set
			{
				if ((this._产品型号 != value))
				{
					this.On产品型号Changing(value);
					this.SendPropertyChanging();
					this._产品型号 = value;
					this.SendPropertyChanged("产品型号");
					this.On产品型号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_生产机台", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> 生产机台
		{
			get
			{
				return this._生产机台;
			}
			set
			{
				if ((this._生产机台 != value))
				{
					if (this._机台.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.On生产机台Changing(value);
					this.SendPropertyChanging();
					this._生产机台 = value;
					this.SendPropertyChanged("生产机台");
					this.On生产机台Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_作业员", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> 作业员
		{
			get
			{
				return this._作业员;
			}
			set
			{
				if ((this._作业员 != value))
				{
					if (this._员工.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.On作业员Changing(value);
					this.SendPropertyChanging();
					this._作业员 = value;
					this.SendPropertyChanged("作业员");
					this.On作业员Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_帘布批号", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid 帘布批号
		{
			get
			{
				return this._帘布批号;
			}
			set
			{
				if ((this._帘布批号 != value))
				{
					if (this._帘布流转.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.On帘布批号Changing(value);
					this.SendPropertyChanging();
					this._帘布批号 = value;
					this.SendPropertyChanged("帘布批号");
					this.On帘布批号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_外胶片批号", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid 外胶片批号
		{
			get
			{
				return this._外胶片批号;
			}
			set
			{
				if ((this._外胶片批号 != value))
				{
					if (this._橡胶薄片1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.On外胶片批号Changing(value);
					this.SendPropertyChanging();
					this._外胶片批号 = value;
					this.SendPropertyChanged("外胶片批号");
					this.On外胶片批号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_内胶片批号", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid 内胶片批号
		{
			get
			{
				return this._内胶片批号;
			}
			set
			{
				if ((this._内胶片批号 != value))
				{
					if (this._橡胶薄片.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.On内胶片批号Changing(value);
					this.SendPropertyChanging();
					this._内胶片批号 = value;
					this.SendPropertyChanged("内胶片批号");
					this.On内胶片批号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_登记时间", DbType="DateTime NOT NULL")]
		public System.DateTime 登记时间
		{
			get
			{
				return this._登记时间;
			}
			set
			{
				if ((this._登记时间 != value))
				{
					this.On登记时间Changing(value);
					this.SendPropertyChanging();
					this._登记时间 = value;
					this.SendPropertyChanged("登记时间");
					this.On登记时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_删除", DbType="Bit NOT NULL")]
		public bool 删除
		{
			get
			{
				return this._删除;
			}
			set
			{
				if ((this._删除 != value))
				{
					this.On删除Changing(value);
					this.SendPropertyChanging();
					this._删除 = value;
					this.SendPropertyChanged("删除");
					this.On删除Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="皮囊成型_皮囊硫化", Storage="_皮囊硫化s", ThisKey="Id", OtherKey="成型皮囊")]
		public EntitySet<皮囊硫化> 皮囊硫化s
		{
			get
			{
				return this._皮囊硫化s;
			}
			set
			{
				this._皮囊硫化s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="机台_皮囊成型", Storage="_机台", ThisKey="生产机台", OtherKey="Id", IsForeignKey=true)]
		public 机台 机台
		{
			get
			{
				return this._机台.Entity;
			}
			set
			{
				机台 previousValue = this._机台.Entity;
				if (((previousValue != value) 
							|| (this._机台.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._机台.Entity = null;
						previousValue.皮囊成型s.Remove(this);
					}
					this._机台.Entity = value;
					if ((value != null))
					{
						value.皮囊成型s.Add(this);
						this._生产机台 = value.Id;
					}
					else
					{
						this._生产机台 = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("机台");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="员工_皮囊成型", Storage="_员工", ThisKey="作业员", OtherKey="Id", IsForeignKey=true)]
		public 员工 员工
		{
			get
			{
				return this._员工.Entity;
			}
			set
			{
				员工 previousValue = this._员工.Entity;
				if (((previousValue != value) 
							|| (this._员工.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._员工.Entity = null;
						previousValue.皮囊成型s.Remove(this);
					}
					this._员工.Entity = value;
					if ((value != null))
					{
						value.皮囊成型s.Add(this);
						this._作业员 = value.Id;
					}
					else
					{
						this._作业员 = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("员工");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="橡胶薄片_皮囊成型", Storage="_橡胶薄片", ThisKey="内胶片批号", OtherKey="Id", IsForeignKey=true)]
		public 橡胶薄片 橡胶薄片
		{
			get
			{
				return this._橡胶薄片.Entity;
			}
			set
			{
				橡胶薄片 previousValue = this._橡胶薄片.Entity;
				if (((previousValue != value) 
							|| (this._橡胶薄片.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._橡胶薄片.Entity = null;
						previousValue.皮囊成型s.Remove(this);
					}
					this._橡胶薄片.Entity = value;
					if ((value != null))
					{
						value.皮囊成型s.Add(this);
						this._内胶片批号 = value.Id;
					}
					else
					{
						this._内胶片批号 = default(System.Guid);
					}
					this.SendPropertyChanged("橡胶薄片");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="橡胶薄片_皮囊成型1", Storage="_橡胶薄片1", ThisKey="外胶片批号", OtherKey="Id", IsForeignKey=true)]
		public 橡胶薄片 橡胶薄片1
		{
			get
			{
				return this._橡胶薄片1.Entity;
			}
			set
			{
				橡胶薄片 previousValue = this._橡胶薄片1.Entity;
				if (((previousValue != value) 
							|| (this._橡胶薄片1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._橡胶薄片1.Entity = null;
						previousValue.皮囊成型s1.Remove(this);
					}
					this._橡胶薄片1.Entity = value;
					if ((value != null))
					{
						value.皮囊成型s1.Add(this);
						this._外胶片批号 = value.Id;
					}
					else
					{
						this._外胶片批号 = default(System.Guid);
					}
					this.SendPropertyChanged("橡胶薄片1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="帘布流转_皮囊成型", Storage="_帘布流转", ThisKey="帘布批号", OtherKey="Id", IsForeignKey=true)]
		public 帘布流转 帘布流转
		{
			get
			{
				return this._帘布流转.Entity;
			}
			set
			{
				帘布流转 previousValue = this._帘布流转.Entity;
				if (((previousValue != value) 
							|| (this._帘布流转.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._帘布流转.Entity = null;
						previousValue.皮囊成型s.Remove(this);
					}
					this._帘布流转.Entity = value;
					if ((value != null))
					{
						value.皮囊成型s.Add(this);
						this._帘布批号 = value.Id;
					}
					else
					{
						this._帘布批号 = default(System.Guid);
					}
					this.SendPropertyChanged("帘布流转");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_皮囊硫化s(皮囊硫化 entity)
		{
			this.SendPropertyChanging();
			entity.皮囊成型 = this;
		}
		
		private void detach_皮囊硫化s(皮囊硫化 entity)
		{
			this.SendPropertyChanging();
			entity.皮囊成型 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.橡胶薄片")]
	public partial class 橡胶薄片 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private double _宽度;
		
		private double _厚度;
		
		private double _数量;
		
		private System.Guid _作业员;
		
		private System.Guid _胶料批号;
		
		private double _生产序号;
		
		private System.DateTime _生产时间;
		
		private System.DateTime _登记时间;
		
		private bool _删除;
		
		private EntitySet<皮囊成型> _皮囊成型s;
		
		private EntitySet<皮囊成型> _皮囊成型s1;
		
		private EntityRef<胶料入库> _胶料入库;
		
		private EntityRef<员工> _员工;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void On宽度Changing(double value);
    partial void On宽度Changed();
    partial void On厚度Changing(double value);
    partial void On厚度Changed();
    partial void On数量Changing(double value);
    partial void On数量Changed();
    partial void On作业员Changing(System.Guid value);
    partial void On作业员Changed();
    partial void On胶料批号Changing(System.Guid value);
    partial void On胶料批号Changed();
    partial void On生产序号Changing(double value);
    partial void On生产序号Changed();
    partial void On生产时间Changing(System.DateTime value);
    partial void On生产时间Changed();
    partial void On登记时间Changing(System.DateTime value);
    partial void On登记时间Changed();
    partial void On删除Changing(bool value);
    partial void On删除Changed();
    #endregion
		
		public 橡胶薄片()
		{
			this._皮囊成型s = new EntitySet<皮囊成型>(new Action<皮囊成型>(this.attach_皮囊成型s), new Action<皮囊成型>(this.detach_皮囊成型s));
			this._皮囊成型s1 = new EntitySet<皮囊成型>(new Action<皮囊成型>(this.attach_皮囊成型s1), new Action<皮囊成型>(this.detach_皮囊成型s1));
			this._胶料入库 = default(EntityRef<胶料入库>);
			this._员工 = default(EntityRef<员工>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_宽度", DbType="Float NOT NULL")]
		public double 宽度
		{
			get
			{
				return this._宽度;
			}
			set
			{
				if ((this._宽度 != value))
				{
					this.On宽度Changing(value);
					this.SendPropertyChanging();
					this._宽度 = value;
					this.SendPropertyChanged("宽度");
					this.On宽度Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_厚度", DbType="Float NOT NULL")]
		public double 厚度
		{
			get
			{
				return this._厚度;
			}
			set
			{
				if ((this._厚度 != value))
				{
					this.On厚度Changing(value);
					this.SendPropertyChanging();
					this._厚度 = value;
					this.SendPropertyChanged("厚度");
					this.On厚度Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_数量", DbType="Float NOT NULL")]
		public double 数量
		{
			get
			{
				return this._数量;
			}
			set
			{
				if ((this._数量 != value))
				{
					this.On数量Changing(value);
					this.SendPropertyChanging();
					this._数量 = value;
					this.SendPropertyChanged("数量");
					this.On数量Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_作业员", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid 作业员
		{
			get
			{
				return this._作业员;
			}
			set
			{
				if ((this._作业员 != value))
				{
					if (this._员工.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.On作业员Changing(value);
					this.SendPropertyChanging();
					this._作业员 = value;
					this.SendPropertyChanged("作业员");
					this.On作业员Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_胶料批号", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid 胶料批号
		{
			get
			{
				return this._胶料批号;
			}
			set
			{
				if ((this._胶料批号 != value))
				{
					if (this._胶料入库.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.On胶料批号Changing(value);
					this.SendPropertyChanging();
					this._胶料批号 = value;
					this.SendPropertyChanged("胶料批号");
					this.On胶料批号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_生产序号", DbType="Float NOT NULL")]
		public double 生产序号
		{
			get
			{
				return this._生产序号;
			}
			set
			{
				if ((this._生产序号 != value))
				{
					this.On生产序号Changing(value);
					this.SendPropertyChanging();
					this._生产序号 = value;
					this.SendPropertyChanged("生产序号");
					this.On生产序号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_生产时间", DbType="DateTime NOT NULL")]
		public System.DateTime 生产时间
		{
			get
			{
				return this._生产时间;
			}
			set
			{
				if ((this._生产时间 != value))
				{
					this.On生产时间Changing(value);
					this.SendPropertyChanging();
					this._生产时间 = value;
					this.SendPropertyChanged("生产时间");
					this.On生产时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_登记时间", DbType="DateTime NOT NULL")]
		public System.DateTime 登记时间
		{
			get
			{
				return this._登记时间;
			}
			set
			{
				if ((this._登记时间 != value))
				{
					this.On登记时间Changing(value);
					this.SendPropertyChanging();
					this._登记时间 = value;
					this.SendPropertyChanged("登记时间");
					this.On登记时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_删除", DbType="Bit NOT NULL")]
		public bool 删除
		{
			get
			{
				return this._删除;
			}
			set
			{
				if ((this._删除 != value))
				{
					this.On删除Changing(value);
					this.SendPropertyChanging();
					this._删除 = value;
					this.SendPropertyChanged("删除");
					this.On删除Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="橡胶薄片_皮囊成型", Storage="_皮囊成型s", ThisKey="Id", OtherKey="内胶片批号")]
		public EntitySet<皮囊成型> 皮囊成型s
		{
			get
			{
				return this._皮囊成型s;
			}
			set
			{
				this._皮囊成型s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="橡胶薄片_皮囊成型1", Storage="_皮囊成型s1", ThisKey="Id", OtherKey="外胶片批号")]
		public EntitySet<皮囊成型> 皮囊成型s1
		{
			get
			{
				return this._皮囊成型s1;
			}
			set
			{
				this._皮囊成型s1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="胶料入库_橡胶薄片", Storage="_胶料入库", ThisKey="胶料批号", OtherKey="Id", IsForeignKey=true)]
		public 胶料入库 胶料入库
		{
			get
			{
				return this._胶料入库.Entity;
			}
			set
			{
				胶料入库 previousValue = this._胶料入库.Entity;
				if (((previousValue != value) 
							|| (this._胶料入库.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._胶料入库.Entity = null;
						previousValue.橡胶薄片s.Remove(this);
					}
					this._胶料入库.Entity = value;
					if ((value != null))
					{
						value.橡胶薄片s.Add(this);
						this._胶料批号 = value.Id;
					}
					else
					{
						this._胶料批号 = default(System.Guid);
					}
					this.SendPropertyChanged("胶料入库");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="员工_橡胶薄片", Storage="_员工", ThisKey="作业员", OtherKey="Id", IsForeignKey=true)]
		public 员工 员工
		{
			get
			{
				return this._员工.Entity;
			}
			set
			{
				员工 previousValue = this._员工.Entity;
				if (((previousValue != value) 
							|| (this._员工.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._员工.Entity = null;
						previousValue.橡胶薄片s.Remove(this);
					}
					this._员工.Entity = value;
					if ((value != null))
					{
						value.橡胶薄片s.Add(this);
						this._作业员 = value.Id;
					}
					else
					{
						this._作业员 = default(System.Guid);
					}
					this.SendPropertyChanged("员工");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_皮囊成型s(皮囊成型 entity)
		{
			this.SendPropertyChanging();
			entity.橡胶薄片 = this;
		}
		
		private void detach_皮囊成型s(皮囊成型 entity)
		{
			this.SendPropertyChanging();
			entity.橡胶薄片 = null;
		}
		
		private void attach_皮囊成型s1(皮囊成型 entity)
		{
			this.SendPropertyChanging();
			entity.橡胶薄片1 = this;
		}
		
		private void detach_皮囊成型s1(皮囊成型 entity)
		{
			this.SendPropertyChanging();
			entity.橡胶薄片1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.帘布流转")]
	public partial class 帘布流转 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _产品编号;
		
		private double _宽度;
		
		private double _厚度;
		
		private double _角度;
		
		private System.Nullable<System.Guid> _作业员;
		
		private System.Guid _帘布批号;
		
		private System.DateTime _使用期限;
		
		private System.DateTime _登记时间;
		
		private bool _删除;
		
		private EntitySet<皮囊成型> _皮囊成型s;
		
		private EntityRef<帘布入库> _帘布入库;
		
		private EntityRef<员工> _员工;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void On产品编号Changing(string value);
    partial void On产品编号Changed();
    partial void On宽度Changing(double value);
    partial void On宽度Changed();
    partial void On厚度Changing(double value);
    partial void On厚度Changed();
    partial void On角度Changing(double value);
    partial void On角度Changed();
    partial void On作业员Changing(System.Nullable<System.Guid> value);
    partial void On作业员Changed();
    partial void On帘布批号Changing(System.Guid value);
    partial void On帘布批号Changed();
    partial void On使用期限Changing(System.DateTime value);
    partial void On使用期限Changed();
    partial void On登记时间Changing(System.DateTime value);
    partial void On登记时间Changed();
    partial void On删除Changing(bool value);
    partial void On删除Changed();
    #endregion
		
		public 帘布流转()
		{
			this._皮囊成型s = new EntitySet<皮囊成型>(new Action<皮囊成型>(this.attach_皮囊成型s), new Action<皮囊成型>(this.detach_皮囊成型s));
			this._帘布入库 = default(EntityRef<帘布入库>);
			this._员工 = default(EntityRef<员工>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_产品编号", DbType="NChar(200) NOT NULL", CanBeNull=false)]
		public string 产品编号
		{
			get
			{
				return this._产品编号;
			}
			set
			{
				if ((this._产品编号 != value))
				{
					this.On产品编号Changing(value);
					this.SendPropertyChanging();
					this._产品编号 = value;
					this.SendPropertyChanged("产品编号");
					this.On产品编号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_宽度", DbType="Float NOT NULL")]
		public double 宽度
		{
			get
			{
				return this._宽度;
			}
			set
			{
				if ((this._宽度 != value))
				{
					this.On宽度Changing(value);
					this.SendPropertyChanging();
					this._宽度 = value;
					this.SendPropertyChanged("宽度");
					this.On宽度Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_厚度", DbType="Float NOT NULL")]
		public double 厚度
		{
			get
			{
				return this._厚度;
			}
			set
			{
				if ((this._厚度 != value))
				{
					this.On厚度Changing(value);
					this.SendPropertyChanging();
					this._厚度 = value;
					this.SendPropertyChanged("厚度");
					this.On厚度Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_角度", DbType="Float NOT NULL")]
		public double 角度
		{
			get
			{
				return this._角度;
			}
			set
			{
				if ((this._角度 != value))
				{
					this.On角度Changing(value);
					this.SendPropertyChanging();
					this._角度 = value;
					this.SendPropertyChanged("角度");
					this.On角度Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_作业员", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> 作业员
		{
			get
			{
				return this._作业员;
			}
			set
			{
				if ((this._作业员 != value))
				{
					if (this._员工.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.On作业员Changing(value);
					this.SendPropertyChanging();
					this._作业员 = value;
					this.SendPropertyChanged("作业员");
					this.On作业员Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_帘布批号", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid 帘布批号
		{
			get
			{
				return this._帘布批号;
			}
			set
			{
				if ((this._帘布批号 != value))
				{
					if (this._帘布入库.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.On帘布批号Changing(value);
					this.SendPropertyChanging();
					this._帘布批号 = value;
					this.SendPropertyChanged("帘布批号");
					this.On帘布批号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_使用期限", DbType="DateTime NOT NULL")]
		public System.DateTime 使用期限
		{
			get
			{
				return this._使用期限;
			}
			set
			{
				if ((this._使用期限 != value))
				{
					this.On使用期限Changing(value);
					this.SendPropertyChanging();
					this._使用期限 = value;
					this.SendPropertyChanged("使用期限");
					this.On使用期限Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_登记时间", DbType="DateTime NOT NULL")]
		public System.DateTime 登记时间
		{
			get
			{
				return this._登记时间;
			}
			set
			{
				if ((this._登记时间 != value))
				{
					this.On登记时间Changing(value);
					this.SendPropertyChanging();
					this._登记时间 = value;
					this.SendPropertyChanged("登记时间");
					this.On登记时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_删除", DbType="Bit NOT NULL")]
		public bool 删除
		{
			get
			{
				return this._删除;
			}
			set
			{
				if ((this._删除 != value))
				{
					this.On删除Changing(value);
					this.SendPropertyChanging();
					this._删除 = value;
					this.SendPropertyChanged("删除");
					this.On删除Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="帘布流转_皮囊成型", Storage="_皮囊成型s", ThisKey="Id", OtherKey="帘布批号")]
		public EntitySet<皮囊成型> 皮囊成型s
		{
			get
			{
				return this._皮囊成型s;
			}
			set
			{
				this._皮囊成型s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="帘布入库_帘布流转", Storage="_帘布入库", ThisKey="帘布批号", OtherKey="Id", IsForeignKey=true)]
		public 帘布入库 帘布入库
		{
			get
			{
				return this._帘布入库.Entity;
			}
			set
			{
				帘布入库 previousValue = this._帘布入库.Entity;
				if (((previousValue != value) 
							|| (this._帘布入库.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._帘布入库.Entity = null;
						previousValue.帘布流转s.Remove(this);
					}
					this._帘布入库.Entity = value;
					if ((value != null))
					{
						value.帘布流转s.Add(this);
						this._帘布批号 = value.Id;
					}
					else
					{
						this._帘布批号 = default(System.Guid);
					}
					this.SendPropertyChanged("帘布入库");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="员工_帘布流转", Storage="_员工", ThisKey="作业员", OtherKey="Id", IsForeignKey=true)]
		public 员工 员工
		{
			get
			{
				return this._员工.Entity;
			}
			set
			{
				员工 previousValue = this._员工.Entity;
				if (((previousValue != value) 
							|| (this._员工.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._员工.Entity = null;
						previousValue.帘布流转s.Remove(this);
					}
					this._员工.Entity = value;
					if ((value != null))
					{
						value.帘布流转s.Add(this);
						this._作业员 = value.Id;
					}
					else
					{
						this._作业员 = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("员工");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_皮囊成型s(皮囊成型 entity)
		{
			this.SendPropertyChanging();
			entity.帘布流转 = this;
		}
		
		private void detach_皮囊成型s(皮囊成型 entity)
		{
			this.SendPropertyChanging();
			entity.帘布流转 = null;
		}
	}
}
#pragma warning restore 1591
