CREATE TABLE [dbo].[检验修边]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT newid(), 
    [结果] BIT NOT NULL DEFAULT 1, 
    [处理方法] UNIQUEIDENTIFIER NOT NULL,
    [检验员] UNIQUEIDENTIFIER NOT NULL, 
    [硫化皮囊] UNIQUEIDENTIFIER NOT NULL, 
    [登记时间] DATETIME NOT NULL DEFAULT getdate(), 
    [删除] BIT NOT NULL DEFAULT 0, 
    CONSTRAINT [FK_检验修边_处理方法] FOREIGN KEY (处理方法) REFERENCES 处理方法(Id), 
    CONSTRAINT [FK_检验修边_员工] FOREIGN KEY (检验员) REFERENCES 员工(Id), 
    CONSTRAINT [FK_检验修边_皮囊硫化] FOREIGN KEY (硫化皮囊) REFERENCES 皮囊硫化(Id)
)
