//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKT.RubberTraceSystem.Data.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<班别> 班别 { get; set; }
        public virtual DbSet<处理方法> 处理方法 { get; set; }
        public virtual DbSet<机台> 机台 { get; set; }
        public virtual DbSet<检验修边> 检验修边 { get; set; }
        public virtual DbSet<胶料入库> 胶料入库 { get; set; }
        public virtual DbSet<帘布流转> 帘布流转 { get; set; }
        public virtual DbSet<帘布入库> 帘布入库 { get; set; }
        public virtual DbSet<皮囊成型> 皮囊成型 { get; set; }
        public virtual DbSet<皮囊硫化> 皮囊硫化 { get; set; }
        public virtual DbSet<橡胶薄片> 橡胶薄片 { get; set; }
        public virtual DbSet<员工> 员工 { get; set; }
    }
}
